services:
  mysql:
    image: mysql:8.0
    container_name: mysql

  environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_reservation

      ports:
        - "3307:3306"

  networks:
    - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:mysql://mysql:3306/gestion_reservation
      DB_USERNAME: root
      DB_PASSWORD: root

      CLOUDINARY_URL: ${CLOUDINARY_URL}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}

      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}

    depends_on:
      - mysql

    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "80:80"

    depends_on:
      - backend

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
