apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment # Doit correspondre exactement au nom dans votre main.yml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: abdellatifmajd123/projet_devops-backend:latest # Votre image Docker Hub
          imagePullPolicy: Always # Force Kubernetes à retélécharger l'image à chaque restart
          ports:
            - containerPort: 8080 # Le port par défaut de Spring Boot
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/devopsdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"

            # On récupère les clés Cloudinary depuis le Secret Kubernetes
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLOUDINARY_API_SECRET

            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: STRIPE_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels: # Permet au ServiceMonitor de trouver ce Service
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http # Doit correspondre exactement au "port: http" du ServiceMonitor
      port: 8080
      targetPort: 8080
  type: ClusterIP
